### ISSUE TITLE
Feature: interactive data visualization panel

### ISSUE THREAD

**Issue by rndsrc** [focisrc/ucast#3]
µcast currently uses `matplotlib` to create summary plots of the weather data.  However, during a VLBI observation, it is useful to see the current time with the most updated weather forecast.  We may use `bokeh` to implement an interactive weather viewing panel.

**Comment by phanicode** [comment]
@rndsrc See https://github.com/phanicode/ucast-viz

I have made a bokeh interactive plot for opacity ( t225?) with toggles for stations.
The command line arguments are python bokeh_plot.py latest ( or latest-X)
I haven't integrated it into the ucast command line yet but this should work fine for now.

**Comment by phanicode** [comment]
TODO: Consider integrating bokeh_plot.py with command line arguments for ucast

**Comment by phanicode** [comment]
@rndsrc 
Do we need a bokeh Tabs layout for this? . I tried to replicate the ucast.png layout but can make changes if necessary.
Also, I'm considering moving label toggles outside the plot as it may slightly obfuscate data in some cases ( although it can be avoided by scroll zooming past it).

**Comment by rndsrc** [comment]
Well done!  I think the current bokeh dashboard is good starting point.
